# This file in in hpack format, see https://github.com/sol/hpack
name: haskell-dev-sprint-calculator
version: 1.0.0
github: "githubuser/haskell-dev-sprint-calculator"
license: BSD3
author: "Jonathan L. Komar"
maintainer: "The Author"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-dev-sprint-calculator#readme>

flags:
  with-examples:
    description: "Build the example files within the examples directory."
    manual: true
    default: false



dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative
  - yaml # auto-documenting encoder and decoder
  - bytestring
  - containers
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  dev-sprint-calculator:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-dev-sprint-calculator
  examples:
    main: Main.hs
    source-dirs: examples
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -ddump-splices # Prints template-haskell stuff and any derive generics stuff
    dependencies:
      - haskell-dev-sprint-calculator
      - raw-strings-qq
      - aeson ## needed for Haskell Templates only
    when:
      - condition: 'flag(with-examples)'
        buildable: false
      - condition: false
        other-modules: 
          - Config_Generics_Deriving_JSON_DTOs

tests:
  haskell-dev-sprint-calculator-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-dev-sprint-calculator
